# Generated by Django 3.2.4 on 2021-06-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('prod_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_brand', models.CharField(max_length=100)),
                ('prod_packet_size', models.CharField(max_length=100)),
                ('prod_packet_type', models.CharField(max_length=100)),
                ('prod_mrp', models.ImageField(upload_to='')),
                ('prod_price', models.ImageField(upload_to='')),
                ('prod_date', models.DateField(auto_now_add=True)),
                ('prod_image', models.ImageField(upload_to='shop/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sub_category')),
            ],
        ),
    ]
