# Generated by Django 3.2.4 on 2021-06-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='prod_mrp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='prod_price',
            field=models.IntegerField(),
        ),
    ]
