# Generated by Django 3.2.4 on 2021-06-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210618_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='prod_image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
