# Generated by Django 3.2.4 on 2021-06-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sub_category_prod_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='prod_image',
            new_name='sub_cat_image',
        ),
    ]
