# Generated by Django 3.2.4 on 2021-07-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_prod_image_sub_category_sub_cat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('sno', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
