# Generated by Django 3.2.4 on 2021-07-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
