# Generated by Django 3.2.4 on 2021-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_contactus_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='prod_mrp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='prod_price',
            field=models.FloatField(),
        ),
    ]
