# Generated by Django 3.2.4 on 2021-08-04 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_auto_20210728_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_image',
            field=models.ImageField(default='', upload_to='shop/images/'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=5000)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=400)),
                ('address2', models.CharField(max_length=400)),
                ('landmark', models.CharField(max_length=200)),
                ('mobileno', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('eprice', models.CharField(max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('packed', models.IntegerField(default=0)),
                ('ondelivery', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
                ('canceled', models.IntegerField(default=0)),
                ('order_return', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
