# Generated by Django 3.2.4 on 2021-08-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orders_cashmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivereddate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
