# Generated by Django 3.2.4 on 2021-08-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orders_delivereddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return_Message',
            fields=[
                ('msg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders')),
            ],
        ),
    ]
