# Generated by Django 3.2.4 on 2021-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_return_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=20)),
            ],
        ),
    ]
