# Generated by Django 3.2.4 on 2021-08-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_mobileno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobileno',
        ),
    ]
